import PublicHeader from "@/Components/PublicHeader";
import Image from "next/image";
import Link from "next/link";
import "./services.css";
import PublicFooter from "@/Components/PublicFooter";
import { getSiteContent } from "@/lib/data/site";
import { getPublicSocialLinks } from "@/lib/data/social";

export const metadata = { title: { absolute: "AI Video Creation & Video Editing Services | Idayat Ibrahim" }, description: "AI video creation, video editing, UGC-style content, product advertisements and commercial storytelling for brands in Nigeria and worldwide.", alternates: { canonical: "https://aivideocreator.cv/services" } };

export default async function ServicesPage() {
  const [site, socialLinks] = await Promise.all([getSiteContent(), getPublicSocialLinks()]);
  const services = [
    { title: "AI commercials & brand films", text: "Give your brand a world of its own. Concept-led films that connect your message, visual identity and audience.", tags: ["Creative direction", "Storyboards", "AI production"], image: "/img8.png", alt: "Cinematic visual from the creative portfolio", format: "01 / MAKE AN IMPRESSION" },
    { title: "Product videos & advertisements", text: "Put the details in the spotlight. Product-led visuals for launches, campaigns and the moments that make people look closer.", tags: ["Product storytelling", "Launch content", "Social formats"], image: "/img6.png", alt: "Fashion and product styling composition", format: "02 / PUT YOUR PRODUCT FIRST" },
    { title: "Social & UGC-style content", text: "Tell a story that belongs in the feed. Short-form, AI-assisted content with a clear opening, purposeful pacing and a strong message.", tags: ["Short-form video", "UGC-style concepts", "Campaign assets"], image: "/img3.png", alt: "Creative visual for short-form storytelling", format: "03 / START A CONVERSATION" },
    { title: "Video editing & post-production", text: "Bring the pieces together. Thoughtful editing, sound and finishing that give existing footage a clear direction and a considered final cut.", tags: ["Video editing", "Sound design", "Final delivery"], image: "/img1.png", alt: "Visual storytelling and post-production example", format: "04 / FIND THE FINAL CUT" },
  ];
  const faqs = [
    ["What should I include in my brief?", "Share your brand, audience, objective, preferred style, where the video will appear, budget and target date. Reference videos and existing brand assets help define the direction."],
    ["How much does a project cost?", "Each project is scoped individually. The quote depends on the concept, number of assets, production requirements and delivery formats. Send a brief to receive a tailored proposal."],
    ["Can you work with my existing footage?", "Yes. Video editing and post-production can start with footage you already have. Share a sample and explain what you want the finished video to achieve."],
    ["Do you work with clients outside Nigeria?", "Yes. Idayat is based in Nigeria and works with brands and creators worldwide. Project briefs, creative reviews and delivery can be handled remotely."],
    ["What about timelines, revisions and usage?", "The schedule, review rounds, final formats and intended usage are agreed in the project scope before work begins. Include any fixed launch date or advertising requirements in your enquiry."],
  ];
  return <main className="services-studio"><PublicHeader site={site} current="/services" />
    <section className="svc-hero svc-wrap">
      <div className="svc-hero-copy"><p className="svc-kicker"><i /> CREATIVE SERVICES · NIGERIA / WORLDWIDE</p><h1>Good ideas.<br />Unforgettable<br /><em>moving images.</em></h1><p className="svc-intro">AI video creation, editing and visual storytelling for brands with something worth saying.</p><div className="svc-actions"><Link className="svc-button" href="/contact">Let’s shape your project <span aria-hidden="true">↗</span></Link><a className="svc-text-link" href="#services">Explore the services ↓</a></div><p className="svc-credit">Concept to final cut. Created with Idayat Ibrahim.</p></div>
      <div className="svc-hero-art"><Image src="/img8.png" alt="Cinematic creative direction from the AI Video Creator portfolio" fill sizes="(max-width: 800px) 92vw, 48vw" priority /><div className="svc-art-label"><span>IMAGINATION, WITH DIRECTION.</span><span>01—04</span></div><div className="svc-art-copy">Made to move.<br /><em>Built to mean something.</em></div><Link href="/work" className="svc-art-link" aria-label="Explore selected work">↗</Link></div>
    </section>
    <div className="svc-disciplines"><span>CONCEPT</span><i>✳</i><span>DIRECTION</span><i>✳</i><span>CREATION</span><i>✳</i><span>EDITING</span><i>✳</i><span>STORYTELLING</span></div>
    <section className="svc-wrap svc-offerings" id="services"><div className="svc-section-head"><div><p className="svc-kicker">THE RIGHT FORMAT FOR YOUR IDEA</p><h2>What can we<br /><em>create together?</em></h2></div><p>A full creative process or support with one part of it. We’ll shape the scope around your message and where it needs to go.</p></div><div className="svc-grid">{services.map(service=><article className="svc-card" key={service.title}><div className="svc-card-image"><Image src={service.image} alt={service.alt} fill sizes="(max-width: 650px) 92vw, 45vw" /><span>{service.format}</span></div><div className="svc-card-copy"><h3>{service.title}</h3><p>{service.text}</p><ul>{service.tags.map(tag=><li key={tag}>{tag}</li>)}</ul><Link href="/contact" aria-label={`Discuss ${service.title}`}>Discuss your project <span aria-hidden="true">↗</span></Link></div></article>)}</div></section>
    <section className="svc-process"><div className="svc-wrap"><div className="svc-section-head"><div><p className="svc-kicker">A CLEAR WAY OF WORKING</p><h2>From “what if”<br />to <em>the final frame.</em></h2></div><p>Creative work works best with a shared direction. Here’s how we get there.</p></div><ol>{[["Share the brief", "Tell me about your audience, objective and the story you want to tell."],["Shape the direction", "We align on the concept, visual references, deliverables and project scope."],["Create & refine", "Production and editing bring the idea to life, with reviews at the agreed stages."],["Deliver the work", "Receive the final assets in the formats agreed for your channels."]].map(([title,body],i)=><li key={title}><span>0{i+1}</span><h3>{title}</h3><p>{body}</p></li>)}</ol></div></section>
    <section className="svc-wrap svc-training"><span className="svc-training-mark" aria-hidden="true">✳</span><div><p className="svc-kicker">FOR THE CREATORS IN THE MAKING</p><h2>Want to learn<br /><em>the craft yourself?</em></h2><p>Explore AI VIDEO CREATOR Academy for practical training in AI-assisted video production, prompting and visual storytelling.</p></div><Link className="svc-button" href="/academy">Explore the Academy <span aria-hidden="true">↗</span></Link></section>
    <section className="svc-wrap svc-faq"><div><p className="svc-kicker">BEFORE WE BEGIN</p><h2>A little<br /><em>clarity.</em></h2></div><div>{faqs.map(([question,answer])=><details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className="svc-end"><p className="svc-kicker">YOUR NEXT IDEA STARTS HERE</p><h2>Let’s make<br /><em>something worth watching.</em></h2><Link className="svc-button" href="/contact">Tell me what you have in mind <span aria-hidden="true">↗</span></Link><Link className="svc-text-link" href="/work">See selected work</Link></section>
    <PublicFooter site={site} socialLinks={socialLinks} /></main>;
}
