"use client";
import {useState,useRef,useEffect} from 'react';
import {Input,Textarea,Select,Button} from '@/Components/FormControls';
import {notify} from '@/Components/ToastHost';
import {emailHtml} from '@/lib/communications-format';
export async function communicationsRequest(data){const r=await fetch('/api/admin/communications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await r.json();if(!r.ok||result.error)throw new Error(result.error||'Request failed.');return result;}
export default function CommunicationsManager({kind='newsletter',initial=[],courses=[],error,studentId=''}){
 const fresh=()=>({id:crypto.randomUUID(),revision:0,subject:'',body:'',state:'draft',filters:{segment:kind==='message'?'paid':'all',status:kind==='message'?'active':'all',ids:studentId?[studentId]:[]}});
 const [draft,setDraft]=useState(fresh),[campaigns,setCampaigns]=useState(initial),[busy,setBusy]=useState(false),[recipients,setRecipients]=useState(null),[preview,setPreview]=useState(false),[mobile,setMobile]=useState(false),[due,setDue]=useState(''),[search,setSearch]=useState(''),[dirty,setDirty]=useState(false);
 const text=useRef(null),testId=useRef(null),lock=useRef(false);
 useEffect(()=>{const handler=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 function edit(patch){testId.current=null;setDraft(d=>({...d,...patch}));setDirty(true);setRecipients(null);}
 function filter(patch){edit({filters:{...draft.filters,...patch}});}
 async function run(fn){if(lock.current)return;lock.current=true;setBusy(true);try{await fn();}catch(e){notify(e.message,'error');}finally{lock.current=false;setBusy(false);}}
 function remember(c){setCampaigns(items=>[c,...items.filter(i=>i.id!==c.id)]);setDraft(c);setDirty(false);}
 async function save(){const {campaign}=await communicationsRequest({action:'save',kind,...draft});remember(campaign);return campaign;}
 function format(before,after=''){const el=text.current,start=el.selectionStart,end=el.selectionEnd;edit({body:draft.body.slice(0,start)+before+(draft.body.slice(start,end)||'text')+after+draft.body.slice(end)});requestAnimationFrame(()=>el.focus());}
 function open(c){if(dirty&&!window.confirm('Discard unsaved changes?'))return;testId.current=null;setDraft(c);setRecipients(null);setDirty(false);}
 if(error)return <p role="alert">{error}</p>;
 const locked=busy||draft.state!=='draft';
 return <div className="communications-grid">
 <aside className="communications-list"><Button type="button" onClick={()=>open(fresh())}>New {kind}</Button><h2>Saved {kind==='template'?'templates':'campaigns'}</h2>{!campaigns.length&&<p>No saved drafts yet.</p>}{campaigns.map(c=><button key={c.id} type="button" onClick={()=>open(c)} aria-current={draft.id===c.id?'true':undefined}><strong>{c.subject||'Untitled draft'}</strong><small>{c.state} ? {new Date(c.created_at).toLocaleDateString()}</small></button>)}</aside>
 <section className="communications-editor"><p role="status">{busy?'Working?':dirty?'Unsaved changes':draft.revision?'Saved':'New draft'}</p>
 {draft.state==='queued'&&<Button variant="secondary" disabled={busy} onClick={()=>run(async()=>{if(!window.confirm('Cancel remaining queued recipients? Email already accepted or in flight cannot be recalled.'))return;await communicationsRequest({action:'cancel',id:draft.id});setDraft(d=>({...d,state:'cancelled'}));notify('Remaining queued emails cancelled.','success');})}>Cancel remaining queue</Button>}
 {kind==='message'&&<p className="status-note">Messages are for essential course information to paid students. Use Newsletters for promotional content; marketing consent is required there.</p>}
 <label>Subject<Input value={draft.subject} maxLength={200} disabled={locked} onChange={e=>edit({subject:e.target.value})}/></label>
 <div className="cw-text-toolbar" role="toolbar" aria-label="Email formatting">{[['Bold','**','**'],['Italic','_','_'],['Heading','\n## ',''],['List','\n- ',''],['Link','[','](https://example.com)'],['Image','\n![','](https://example.com/image.jpg)'],['CTA button','\nCTA:[','](https://example.com)']].map(([label,a,b])=><Button key={label} type="button" variant="secondary" disabled={locked} onClick={()=>format(a,b)}>{label}</Button>)}</div>
 <label>Message<Textarea ref={text} rows={12} value={draft.body} disabled={locked} onChange={e=>edit({body:e.target.value})}/></label><small>Personalize with {'{{student_name}}'} and {'{{course_title}}'}. Links and images must use HTTPS.</small>
 <div className="communications-actions"><Button disabled={locked} onClick={()=>run(async()=>{await save();notify('Draft saved.','success');})}>Save draft</Button><Button variant="secondary" onClick={()=>setPreview(!preview)}>Preview</Button><Button variant="secondary" disabled={busy||!draft.revision} onClick={()=>run(async()=>{const r=await communicationsRequest({action:'duplicate',kind,id:draft.id});remember(r.campaign);})}>Duplicate</Button></div>
 {preview&&<section><label className="check-label"><input type="checkbox" checked={mobile} onChange={e=>setMobile(e.target.checked)}/>Mobile email preview</label><iframe title="Email preview" sandbox="" srcDoc={emailHtml(draft.body,{student_name:'Student name',course_title:'Course title'})} style={{width:'100%',maxWidth:mobile?375:650,height:480,border:'1px solid #ddd',background:'#fff'}}/></section>}
 {kind!=='template'&&<><h2>Audience</h2><div className="communications-filters"><label>Segment<Select disabled={locked||kind==='message'} value={draft.filters.segment||'all'} onChange={e=>filter({segment:e.target.value})}><option value="all">All subscribed students</option><option value="paid">Paid students{kind==='newsletter'?' who opted in':''}</option><option value="free">Free students who opted in</option></Select></label><label>Course<Select disabled={locked} value={draft.filters.courseId||''} onChange={e=>filter({courseId:e.target.value})}><option value="">All courses</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</Select></label><label>Enrollment status<Select disabled={locked} value={draft.filters.status||'active'} onChange={e=>filter({status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option><option value="all">All</option></Select></label><label>Enrolled from<Input disabled={locked} type="date" value={draft.filters.from||''} onChange={e=>filter({from:e.target.value})}/></label><label>Enrolled through<Input disabled={locked} type="date" value={draft.filters.to||''} onChange={e=>filter({to:e.target.value})}/></label></div>
 <Button disabled={locked} variant="secondary" onClick={()=>run(async()=>{const r=await communicationsRequest({action:'audience',kind,filters:{...draft.filters,ids:[]}});setRecipients(r.recipients);})}>Review eligible recipients</Button>
 {recipients&&<div className="communications-recipients"><label>Search recipients<Input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><p>{draft.filters.ids?.length||recipients.length} recipients selected. Consent and eligibility are checked again before delivery.</p><Button variant="secondary" disabled={locked} onClick={()=>{setDraft(d=>({...d,filters:{...d.filters,ids:[]}}));setDirty(true);}}>Select all eligible</Button>{recipients.filter(r=>`${r.student_name} ${r.email}`.toLowerCase().includes(search.toLowerCase())).map(r=><label key={r.student_id} className="check-label"><input type="checkbox" disabled={locked} checked={!draft.filters.ids?.length||draft.filters.ids.includes(r.student_id)} onChange={e=>{const current=draft.filters.ids?.length?draft.filters.ids:recipients.map(x=>x.student_id);const next=e.target.checked?[...current,r.student_id]:current.filter(x=>x!==r.student_id);if(!next.length){notify('Select at least one recipient.','error');return;}setDraft(d=>({...d,filters:{...d.filters,ids:next}}));setDirty(true);}}/>{r.student_name} ? {r.email}</label>)}</div>}
 <label>Schedule (your device?s local time; leave blank to queue now)<Input disabled={locked} type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label>
 <div className="communications-actions"><Button variant="secondary" disabled={locked||!draft.subject||!draft.body} onClick={()=>run(async()=>{const c=await save();testId.current||=crypto.randomUUID();await communicationsRequest({action:'test',id:c.id,testId:testId.current});notify('Test queued to your administrator email.','success');})}>Queue test to my email</Button><Button disabled={locked||!recipients?.length||!draft.subject||!draft.body} onClick={()=>run(async()=>{const c=await save();const r=await communicationsRequest({action:'audience',kind,filters:c.filters});if(!r.count)throw new Error('No eligible recipients.');if(!window.confirm(`${due?'Schedule':'Queue'} this ${kind} to ${r.count} recipients?`))return;const result=await communicationsRequest({action:'queue',id:c.id,revision:c.revision,confirm:true,due:due?new Date(due).toISOString():null});setDraft(d=>({...d,state:'queued'}));notify(`${result.count} emails queued. The background scheduler sends due messages.`,'success');})}>{due?'Schedule campaign':'Confirm and queue'}</Button></div></>}
 {kind==='template'&&draft.revision>0&&<div className="communications-actions">{['message','newsletter'].map(k=><Button key={k} variant="secondary" disabled={busy} onClick={()=>run(async()=>{await communicationsRequest({action:'duplicate',id:draft.id,kind:k});notify(`Draft created in ${k==='message'?'Messages':'Newsletters'}.`,'success');})}>Use for {k}</Button>)}</div>}
 </section></div>;
}
