"use client";
import { Input, Select, Textarea } from "@/Components/FormControls";

import { useState } from "react";
import useCourseFormCapture from "@/Components/useCourseFormCapture";
import CourseCoverField from "@/Components/CourseCoverField";
import CourseVideoPlayer from "@/Components/CourseVideoPlayer";
import { getCourseVideoSource } from "@/lib/course-video-source";

export default function CourseForm({ course, action, step = "details", onDraftChange }) {
  const formRef = useCourseFormCapture(onDraftChange); const [free, setFree] = useState(course?.isFree ?? true); const [price, setPrice] = useState(course ? course.priceMinor / 100 : 0); const [discount, setDiscount] = useState(course?.discountedPriceMinor == null ? "" : course.discountedPriceMinor / 100); const [currency, setCurrency] = useState(course?.currency || "NGN"); const [promoUrl, setPromoUrl] = useState(course?.promotionalVideoUrl || ""); const [promoOrientation, setPromoOrientation] = useState(course?.promotionalOrientation || "landscape"); const lines = (value) => Array.isArray(value) ? value.join("\n") : ""; const promo = getCourseVideoSource(promoUrl); const previewAmount = discount !== "" && Number(discount) >= 0 && Number(discount) <= Number(price) ? discount : price;
  return <form ref={formRef} noValidate className="admin-form course-admin-form" onSubmit={event => { event.preventDefault(); action(); }}>
    <Input type="hidden" name="id" value={course?.id || ""} /><Input type="hidden" name="step" value={step} />
    {step === "details" && <>
      <label>Title<Input name="title" defaultValue={course?.title} required /></label><label>Slug<Input name="slug" defaultValue={course?.slug} pattern="[a-z0-9]+(-[a-z0-9]+)*" required /></label>
      <label className="form-wide">Short description<Textarea name="shortDescription" rows="2" defaultValue={course?.shortDescription} /></label><label className="form-wide">Full description<Textarea name="description" rows="7" defaultValue={course?.description} /></label>
      <CourseCoverField course={course} /><details className="form-wide cw-options"><summary>Course settings & instructor</summary><div className="cw-options-grid"><label>Instructor<Input name="instructor" defaultValue={course?.instructor} /></label><label>Category<Input name="category" defaultValue={course?.category} /></label>
      <label>Difficulty<Select name="difficulty" defaultValue={course?.difficulty || "All levels"}><option>Beginner</option><option>Intermediate</option><option>Advanced</option><option>All levels</option></Select></label><label>Language<Input name="language" defaultValue={course?.language || "English"} /></label><label>Estimated duration<Input name="estimatedDuration" defaultValue={course?.estimatedDuration} placeholder="4 hours" /></label></div></details>
      <details className="form-wide cw-options"><summary>Promotional video (optional)</summary><label className="form-wide">Promotional video (YouTube, Vimeo or Google Drive)<Input type="url" name="promotionalVideoUrl" value={promoUrl} onChange={(event) => setPromoUrl(event.target.value)} placeholder="https://..." /></label><label>Promotional video format<Select name="promotionalOrientation" value={promoOrientation} onChange={(event) => setPromoOrientation(event.target.value)}><option value="landscape">16:9 landscape</option><option value="portrait">9:16 portrait</option></Select></label>
      {promoUrl && <section className="lesson-source-preview form-wide">{promo ? <CourseVideoPlayer lesson={{ id: "promo", title: "Promotional video", sourceType: promo.sourceType, embedUrl: promo.embedUrl, orientation: promoOrientation, aspectRatio: promoOrientation === "portrait" ? 9 / 16 : 16 / 9 }} admin /> : <p className="form-error">That promotional video link is not recognised.</p>}</section>}
      </details><details className="form-wide cw-options"><summary>Learning outcomes, prerequisites & audience</summary><label className="form-wide">Learning outcomes, one per line<Textarea name="learningOutcomes" rows="5" defaultValue={lines(course?.learningOutcomes)} /></label><label className="form-wide">Requirements, one per line<Textarea name="requirements" rows="4" defaultValue={lines(course?.requirements)} /></label><label className="form-wide">Target audience, one per line<Textarea name="targetAudience" rows="4" defaultValue={lines(course?.targetAudience)} /></label>
      </details><details className="form-wide cw-options"><summary>Search & social preview (optional)</summary><label>SEO title<Input name="seoTitle" defaultValue={course?.seoTitle} /></label><label>Open Graph image URL<Input type="url" name="ogImageUrl" defaultValue={course?.ogImageUrl} /></label><label className="form-wide">SEO description<Textarea name="seoDescription" rows="3" defaultValue={course?.seoDescription} /></label></details>
    </>}
    {step === "pricing" && <>
      <label className="check-label form-wide"><Input type="checkbox" name="isFree" checked={free} onChange={(event) => setFree(event.target.checked)} />This is a free course</label>
      {!free && <><label>Regular price<Input type="number" name="price" min="0.01" step="0.01" value={price} onChange={(event) => setPrice(event.target.value)} required /></label><label>Sale price<Input type="number" name="discountedPrice" min="0" step="0.01" value={discount} onChange={(event) => setDiscount(event.target.value)} /></label><label>Currency<Input name="currency" maxLength="3" value={currency} onChange={(event) => setCurrency(event.target.value.toUpperCase())} required /></label><label>Gateway<Input value="Bachs" disabled /><small>Checkout always uses the server-side course price.</small></label><label>Sale starts<Input type="datetime-local" name="saleStartsAt" defaultValue={course?.saleStartsAt?.slice(0, 16)} /></label><label>Sale ends<Input type="datetime-local" name="saleEndsAt" defaultValue={course?.saleEndsAt?.slice(0, 16)} /></label></>}
      {free && <><Input type="hidden" name="price" value="0" /><Input type="hidden" name="currency" value={course?.currency || "NGN"} /></>}
      <label className="check-label form-wide"><Input type="checkbox" name="featured" defaultChecked={course?.featured} />Feature this course publicly</label>
      <section className="course-price-preview form-wide"><small>Student price preview</small><strong>{free ? "Free" : `${currency} ${Number(previewAmount || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`}</strong>{!free && discount !== "" && <p><s>{currency} {Number(price || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</s> during the configured sale window.</p>}<p>Free courses allow signed-in enrolment. Paid courses require checkout. You can also grant or revoke individual access from the course Students page.</p></section>
    </>}

  </form>;
}
