import { Input, Textarea, Button } from "@/Components/FormControls";
import { PageHeader } from "@/Components/DashboardPageShell";
import Link from "next/link";
import ProfileImageField from "@/Components/ProfileImageField";
import { getSiteContent } from "@/lib/data/site";
import { saveSiteContent } from "@/app/admin/actions";

export default async function HeroContent({ searchParams }) {
  const [site, query] = await Promise.all([getSiteContent(), searchParams]);
  return <><PageHeader title={<>Hero & identity</>} eyebrow={<>WEBSITE CONTENT</>} actions={<><Link href="/">Preview website</Link></>}/>{query.saved && <p className="success-note">Website content updated.</p>}<form className="admin-form" action={saveSiteContent}><label>Creator name<Input name="creatorName" defaultValue={site.creatorName} required /></label><ProfileImageField site={site} /><label className="form-wide">Hero heading<Input name="heroHeading" defaultValue={site.heroHeading} required /></label><label>Highlighted word<Input name="highlightWord" defaultValue={site.highlightWord} required /></label><label>CTA label<Input name="ctaLabel" defaultValue={site.ctaLabel} required /></label><label className="form-wide">Hero supporting copy<Textarea name="heroCopy" defaultValue={site.heroCopy} rows="3" required /></label><label>CTA destination<Input name="ctaHref" defaultValue={site.ctaHref} required /></label><label>Accent colour<Input name="accentColor" type="color" defaultValue={site.accentColor} /></label><label>Background colour<Input name="lightBackground" type="color" defaultValue={site.lightBackground} /></label><Input type="hidden" name="aboutHeading" value={site.aboutHeading} /><Input type="hidden" name="aboutCopy" value={site.aboutCopy} /><Input type="hidden" name="contactHeading" value={site.contactHeading} /><Input type="hidden" name="contactCopy" value={site.contactCopy} /><Input type="hidden" name="publicEmail" value={site.publicEmail} /><Input type="hidden" name="phone" value={site.phone} /><Input type="hidden" name="instagramUrl" value={site.instagramUrl} /><Input type="hidden" name="youtubeUrl" value={site.youtubeUrl} /><Input type="hidden" name="footerText" value={site.footerText} /><Button className="button">Save hero</Button></form></>;
}
