import { Input, Button } from "@/Components/FormControls";
import { PageHeader } from "@/Components/DashboardPageShell";
import ConfirmSubmitButton from "@/Components/ConfirmSubmitButton";
import { randomUUID } from "node:crypto";
import { notFound } from "next/navigation";
import CourseWorkflowNav from "@/Components/CourseWorkflowNav";
import CourseLessonEditor from "@/Components/CourseLessonEditor";
import CurriculumReorder from "@/Components/CurriculumReorder";
import AdminToast from "@/Components/AdminToast";
import { getAdminCourse } from "@/lib/data/courses";
import { deleteCourseLesson, deleteCourseResource, deleteCourseSection, duplicateCourseLesson, saveCourseLesson, saveCourseSection } from "@/app/admin/actions";

function ResourceEditor({ course, lesson }) {
  return <section className="resource-admin"><h3>Private lesson PDFs</h3>{lesson.resources.map((resource) => <div key={resource.id} className="resource-row"><span><strong>{resource.title}</strong>{resource.description && <> · {resource.description}</>} · <a href={`/api/learn/resources/${resource.id}?admin=1`} target="_blank" rel="noreferrer">Preview</a></span><details><summary>Replace</summary><form action="/api/admin/course-resource" method="post" encType="multipart/form-data"><Input type="hidden" name="courseId" value={course.id} /><Input type="hidden" name="lessonId" value={lesson.id} /><Input type="hidden" name="replacementId" value={resource.id} /><label>Title<Input name="title" defaultValue={resource.title} required /></label><label>Description<Input name="description" defaultValue={resource.description} /></label><label>New PDF<Input type="file" name="file" accept="application/pdf,.pdf" required /></label><label className="check-label"><Input type="checkbox" name="allowDownload" defaultChecked={resource.allowDownload} />Allow download</label><label className="check-label"><Input type="checkbox" name="previewAllowed" defaultChecked={resource.previewAllowed} />Allow public preview</label><Button className="button">Replace safely</Button></form></details><form action={deleteCourseResource}><Input type="hidden" name="id" value={resource.id} /><Input type="hidden" name="courseId" value={course.id} /><Button>Remove</Button></form></div>)}<form action="/api/admin/course-resource" method="post" encType="multipart/form-data"><Input type="hidden" name="courseId" value={course.id} /><Input type="hidden" name="lessonId" value={lesson.id} /><label>Title<Input name="title" required /></label><label>Description<Input name="description" /></label><label>PDF<Input type="file" name="file" accept="application/pdf,.pdf" required /></label><label className="check-label"><Input type="checkbox" name="allowDownload" />Allow download</label><label className="check-label"><Input type="checkbox" name="previewAllowed" />Allow public preview</label><Button className="button">Upload PDF</Button></form></section>;
}

export default async function CurriculumPage({ params, searchParams }) {
  const [{ id }, query] = await Promise.all([params, searchParams]); const course = await getAdminCourse(id); if (!course) notFound(); const saved = query.saved === "section" ? "Section saved." : query.saved === "lesson" ? "Lesson saved." : query.saved === "resource" ? "Resource saved." : query.saved === "duplicated" ? "Lesson duplicated as a draft." : query.saved === "deleted" ? "Curriculum item deleted." : "";
  return <><PageHeader title={<>{course.title} curriculum</>} eyebrow={<>COURSES</>} description={<>Build your course module by module. Add lessons and resources inside each module, arrange their order, then preview before publishing. Draft lessons stay hidden from students.</>}/><CourseWorkflowNav courseId={id} course={course} active="curriculum" /><AdminToast message={query.error || saved} kind={query.error ? "error" : "success"} /><CurriculumReorder courseId={course.id} sections={course.sections} />
    <section className="curriculum-editor">{course.sections.map((section) => <article key={section.id} className="curriculum-section"><form className="admin-form compact" action={saveCourseSection}><Input type="hidden" name="id" value={section.id} /><Input type="hidden" name="courseId" value={course.id} /><label>Module title<Input name="title" defaultValue={section.title} required /></label><label>Description<Input name="description" defaultValue={section.description} /></label><Button className="button">Update module</Button><ConfirmSubmitButton formAction={deleteCourseSection} message="Delete this module and all of its lessons? This cannot be undone.">Delete module</ConfirmSubmitButton></form>
      {section.lessons.map((lesson) => <details key={lesson.id} className="lesson-editor"><summary>{lesson.title}<small>{lesson.status}{lesson.isPreview ? " · free preview" : ""}</small></summary><CourseLessonEditor course={course} section={section} sections={course.sections} lesson={lesson} lessonId={lesson.id} saveAction={saveCourseLesson} deleteAction={deleteCourseLesson} duplicateAction={duplicateCourseLesson} /><ResourceEditor course={course} lesson={lesson} /></details>)}
      <details className="lesson-editor"><summary>Add lesson to {section.title}</summary><CourseLessonEditor course={course} section={section} sections={course.sections} lessonId={randomUUID()} saveAction={saveCourseLesson} deleteAction={deleteCourseLesson} duplicateAction={duplicateCourseLesson} /></details></article>)}</section>
    <form className="admin-form compact" action={saveCourseSection}><Input type="hidden" name="courseId" value={course.id} /><label>New module title<Input name="title" required /></label><label>Description<Input name="description" /></label><Button className="button">Add module</Button></form>
  </>;
}
