import SettingsNavigation from "@/Components/SettingsNavigation";
import { Input, Select, Button } from "@/Components/FormControls";
import { PageHeader } from "@/Components/DashboardPageShell";
import { getAdminSocialLinks, socialPlatformLabels } from "@/lib/data/social";
import { deleteSocialLink, moveSocialLink, saveSocialLink } from "@/app/admin/actions";

export default async function SocialSettingsPage({ searchParams }) {
  const [links, query] = await Promise.all([getAdminSocialLinks(), searchParams]);
  return <><PageHeader title={<>Social profiles</>} eyebrow={<>SETTINGS</>} description={<>Only enabled profiles with valid destinations appear on public pages.</>}/><SettingsNavigation/>{query.saved && <p className="success-note">Social links updated.</p>}{query.error && <p className="form-error">{query.error}</p>}<section className="social-admin-list">{links.map((link, index) => <form key={link.id} action={saveSocialLink} className="social-admin-row"><Input type="hidden" name="id" value={link.id} /><label>Platform<Select name="platform" defaultValue={link.platform}>{Object.entries(socialPlatformLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></label><label>Label<Input name="label" defaultValue={link.label} required /></label><label>URL<Input name="url" defaultValue={link.url} required /></label><label className="check-label"><Input type="checkbox" name="enabled" defaultChecked={link.enabled} />Enabled</label><Button className="button">Save</Button><div className="social-order-actions"><Button variant="secondary" formAction={moveSocialLink} name="direction" value="up" disabled={index === 0}>Move up</Button><Button variant="secondary" formAction={moveSocialLink} name="direction" value="down" disabled={index === links.length - 1}>Move down</Button><Button variant="danger" formAction={deleteSocialLink}>Remove</Button></div></form>)}</section><form className="admin-form compact" action={saveSocialLink}><label>Platform<Select name="platform" defaultValue="instagram">{Object.entries(socialPlatformLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></label><label>Label<Input name="label" required /></label><label className="form-wide">URL<Input name="url" placeholder="https://…" required /></label><label className="check-label"><Input type="checkbox" name="enabled" defaultChecked />Enabled</label><Button className="button">Add profile</Button></form></>;
}
